### live server test 

GET http://localhost:8000/api/v1/product


### post product

POST http://localhost:8000/api/v1/product
Content-Type: application/json
    
    {
        "status": "inactive",
        "name": "product2",
        "type": "",
        "cost": 900,
        "description": "product1 description"
    }



### UPDATE product

PUT http://localhost:8000/api/v1/product
Content-Type: application/json
    
    {
        "_id":"62d3a6f205f86c3aabb1f271",
        "status": "active",
        "name": "Bibek",
        "type": "andrew",
        "cost": 300,
        "description": "product1 description"
    }


### delete product

DELETE  http://localhost:8000/api/v1/product/62d394c182e0255a91613441
